### PR TITLE
Add go license

### PR DESCRIPTION
**Pull request by lulf**
I'm not proud of this, but until PNC has the license tools fetching this information available, I think this is the best we can do.

### CODE REVIEW

**Review by vbusch — APPROVED** [review]
Looks like we will need to check if licenses.txt needs to be updated on every release.  But that seems reasonable since it is one of the prod-gates.

**Comment by lulf** [comment]
I will add some documentation on how to generate the files

**Comment by lulf** [comment]
@vbusch could you have another look? I have added a script to regenerate licenses and documentation for it.

**Review by vbusch — APPROVED** [review]
Thank you.  Looks Good.

**Pull request merged**
