### PR TITLE
Corrected the artifact path

### PR DESCRIPTION
**Pull request by vbusch**
Updated the artifact path for the cacheartifactall tag, which caches the artifacts, and updates the MD5sum in the module.yaml files

Signed-off-by: Vanessa Busch <vbusch@redhat.com>

### CODE REVIEW

**Review by lulf — APPROVED** [review]

**Comment by lulf** [comment]
@vbusch There are no md5sum update in this PR, but I don't think that should be necessary given that we don't specify them here anymore.

**Comment by vbusch** [comment]
@lulf I am curious about your comment about not specifying them anymore.  Does that mean they shouldn't be in the console-server/ modules/install-artifact/module.yaml file anymore?  And if that is the case, how does the image find the artifact?
The target cacheartifactall updates the md5 to match my locally built artifacts, so it wouldn't be appropriate to commit those changes.
Here is the output from the target:
```
make[1]: Entering directory '/home/vbusch/devel/enmasseproject/amq-online-images/console-server'
cekit-cache add /home/vbusch/devel/enmasseproject/amq-online-images/console-server/../../enmasse-gerrit/console/console-server/target/console-server-0.32-SNAPSHOT-dist.zip --md5 368c76b945537fabdf77dac0f2b97d87
2020-06-15 09:00:45,826 cekit        WARNING  No value found for 'name' in '{"md5": "368c76b945537fabdf77dac0f2b97d87", "url": "/home/vbusch/devel/enmasseproject/amq-online-images/console-server/../../enmasse-gerrit/console/console-server/target/console-server-0.32-SNAPSHOT-dist.zip"}' artifact; using auto-generated value of 'console-server-0.32-SNAPSHOT-dist.zip'
Artifact /home/vbusch/devel/enmasseproject/amq-online-images/console-server/../../enmasse-gerrit/console/console-server/target/console-server-0.32-SNAPSHOT-dist.zip is already cached!
sed -i 's/- md5:.*/- md5: 368c76b945537fabdf77dac0f2b97d87/' modules/install-artifact/module.yaml 
make[1]: Leaving directory '/home/vbusch/devel/enmasseproject/amq-online-images/console-server'



```

**Comment by lulf** [comment]
@vbusch In the productization pipeline (cpaas), the artifacts are automatically copied to the image and an overrides file with the artifacts are injected and used as part of the build. This way, we don't have to update the md5 in the repo for each build anymore.

Maybe having something similar as part of the make target something that would allow you to generate the overrides file and use that in a scratch build?

**Comment by vbusch** [comment]
I'll merge this to have the correct path for the console-server.
And then create another PR for updating the _cacheartifact_ to create/update an override file, instead of updating the module.yaml files.

**Pull request merged**
